### ISSUE TITLE
More configuration examples

### ISSUE THREAD

**Issue by codekuu** [codekuu/pyprojectviz#3]
Add more configuration examples depending on project size.
Some projects require for example:
```
graphviz:
  graph_attr:
    rankdir: TB
    ranksep: "2"
    nodesep: "1"
```

Due to the size.
